### ISSUE TITLE
Feature Proposal: rules

### ISSUE THREAD

**Issue by loeffel-io** [loeffel-io/ls-lint#120]
Reusable rules with a new configuration item `rules` to avoid multiple regex patterns for different extensions

Example: 

```yaml
rules:
    VueComponent: PascalCase
    CustomRule: regex:[a-z0-9]+

ls: 
   .js: VueComponent
   .yaml: CustomRule
```

This is planned for `v2.2.0`
