### ISSUE TITLE
Feature proposal: groups

### ISSUE THREAD

**Issue by loeffel-io** [loeffel-io/ls-lint#121]
Reusable rules with a new configuration item `groups` to group file extensions

Example:

```yaml
groups: 
    images: 
        - .png
        - .jpg
        - .jpeg
        - .gif

ls:
    [images]: kebab-case
```

This is planned for `v2.3.0`
