### ISSUE TITLE
Feature request: ignore abbreviations

### ISSUE THREAD

**Issue by iendeavor** [loeffel-io/ls-lint#167]
I'm wondering if this is useful to anyone else 🤔:

```diff
ls:
  packages/*/{src,__tests__}:
    .js: kebab-case
    .ts: camelCase | PascalCase
    .d.ts: camelCase
    .spec.ts: camelCase | PascalCase
    .mock.ts: camelCase

ignore:
  - node_modules
+
+ abbr:
+  - HTTP
+  - SMS
```

Thank you~

**Comment by loeffel-io** [comment]
Hey @iendeavor, could you please provide more context 

thank you

**Comment by iendeavor** [comment]
Hi, @loeffel-io 
Thanks for your quick reply.

For example, we might have some files containing the abbreviation "SMS", but it violates the PascalCase rule:

```yml
ls:
  .ts: PascalCase
```

```
path/
│
└─ to/
  │
  ├─ EmailService.ts # valid
  │
  └─ SMSService.ts # invalid
```

**Comment by loeffel-io** [comment]
Hey @iendeavor 

for this you can use the regex rule and allow only specific values or the negative of them with something like

```yaml
ls:
    to:
         .ts: regex:(Email|Foo|Bla)Service
```

**Comment by iendeavor** [comment]
Yes, this makes sense for the example mentioned earlier, but we may have any name anywhere in the filename, and we also want to validate it based on specific rules, like:

```
ls:
  .ts: camelCase
```

https://github.com/facebook/react-native/tree/6e42c98aa3423cfbc389e4fe877b5c6b559c8a81/packages/community-cli-plugin/src/commands/bundle

```
../
│
└─ bundle/
  │
  ├─ assetCatalogIOS.js
  │
  ├─ getAssetDestPathIOS.js
  │
  └─ __tests__/
    │
    └─ getAssetDestPathIOS-test.js
```

**Comment by loeffel-io** [comment]
what about 

```yaml
ls:
    to:
         .ts: regex:(Email|Foo|Bla)Service | camelCase # allow EmailService, FooService, BlaService
```
