### ISSUE TITLE
Feature proposal: supporting .dir only for child folders

### ISSUE THREAD

**Issue by haili042** [loeffel-io/ls-lint#199]
Hi~

I have project like this:
```
src
|-- apps
|   |-- HomeApp # XxxXxxApp
|   |   |-- components
|   |   |-- utils
|   |-- UserApp
```

I want all child folders of src/apps follow PascalCase + App, and the other subdirectories follow kebab-case, so I try this:

```yaml
ls: 
  src: 
    .dir: kebab-case

  src/apps:
    .dir:  regex:^[A-Z](([a-z0-9]+[A-Z]?)*)App$
```

```bash
src/apps/HomeApp/components failed for rules: kebabcase
```
But it's fail because .dir will applies for the current directory and all their subdirectories.
So I'd like to propose the ability to supporting rules configuration to add recursive option (or other options maybe)

```yaml
ls: 
  src: 
    .dir: kebab-case

  src/apps:
    .dir: 
      rule: regex:^[A-Z](([a-z0-9]+[A-Z]?)*)App$
      recursive: false # true for all subdirectories, false for child folders
```
