### ISSUE TITLE
Rule: Exists

### ISSUE THREAD

**Issue by tobiastimm** [loeffel-io/ls-lint#30]
It would be cool if this would have a check to ensure that a directory/file exists!

**Comment by loeffel-io** [comment]
Yea, also thought about this but its not that easy to implement 
Will put this on the wishlist

**Comment by loeffel-io** [comment]
How you would solve this in your config?

**Comment by tobiastimm** [comment]
Would be cool to have something like
```
ls:
    packages/src:
        .dir: 
             name: /REGEX_PATTERN/
             exists: true
```
Pretty similar to how [goss](https://github.com/aelsabbahy/goss) handles that
```
user:
  sshd:
    exists: true
    uid: 74
    gid: 74
    groups:
    - sshd
    home: /var/empty/sshd
    shell: /sbin/nologin
```
