### ISSUE TITLE
BUG: windows paths are not working

### ISSUE THREAD

**Issue by ascholz-cariad** [loeffel-io/ls-lint#307]
Hi,

I can't get the regex directory substitution to work. I am using v.2.3.0.

```yml
ls:
  "gen/*/data":
    ".dd.json": regex:${1}
```

It produces:
```txt
`gen/swu1/data/swu1.dd.json failed for `.dd.json` rules: regex:${1}`
```

Is this intended? Am I using it wrong?
