### ISSUE TITLE
Problem with nested rules

### ISSUE THREAD

**Issue by tobiastimm** [loeffel-io/ls-lint#31]
I have the following `.ls-lint.yml`:

```
ls:
  services/*/components/*/__tests__:
    .test.ts: PascalCase
  services/*/:
    .vue: PascalCase
    .ts: kebab-case
```

I want that every TypeScript file validates against `kebab-case` except the ones within the components `__tests__` directory.

The console is throwing errors that within `../components/Button/__tests__/`
`Button.test.ts`
has not a file-name with kebab-case

Is this intended? I would assume that more specialized rules overwrite the general ones

**Comment by loeffel-io** [comment]
This should work pretty fine 
Could you try to swap the directories like 

```yaml
ls:
  services/*/:
    .vue: PascalCase
    .ts: kebab-case
  services/*/components/*/__tests__:
    .test.ts: PascalCase
```
