### ISSUE TITLE
ls-lint does not work when provided files have fullpath (like lint-staged provides)

### ISSUE THREAD

**Issue by HansAarneLiblik** [loeffel-io/ls-lint#321]
Hi!

After upgrading ls-lint from 2.2.3 -> 2.3.0 (or 2.3.1), running it via lint-staged is not working correctly anymore

I think the issue is because in our setup, we expect the files to have relative path to the config file(?), but lint-staged provides files with full path

This is my test project tree

![Image](https://github.com/user-attachments/assets/0de49e76-83eb-4b8e-a433-fbfe9d7dea91)

and here is the output of different commands

`ls-lint` fails as expected
```
➜  testing git:(master) ✗ pnpm ls-lint
react/src/components/a.tsx failed for `.tsx` rules: regex:common(_[a-z]+)* | pascalcase
```

`ls-lint` fails when given relative path as expected
```
➜  testing git:(master) ✗ pnpm ls-lint react/src/components/a.tsx
react/src/components/a.tsx failed for `.tsx` rules: regex:common(_[a-z]+)* | pascalcase
```

`lint-staged` does not fail
```
➜  testing git:(master) ✗ pnpm lint-staged
✔ Preparing lint-staged...
✔ Running tasks for staged files...
✔ Applying modifications from tasks...
```

`ls-lint` does not fail when given full path (like `lint-staged` provides) 
```
➜  testing git:(master) ✗ pnpm ls-lint /Users/HansAarne.Liblik/code/testing/react/src/components/a.tsx
```

Output of `lint-staged --debug`
![Image](https://github.com/user-attachments/assets/4988d52e-99db-428c-b506-9ff1f5c36b24)

Here is my minified `.ls-lint.yml` config
```
ls:
  react/src/components:
    .tsx: regex:common(_[a-z]+)* | PascalCase

ignore:
  - react/coverage
  - node_modules
  - .git
  - .husky
  - .idea
  - .mypy_cache
  - .pytest_cache
  - .ruff_cache
  - _local
```
