### ISSUE TITLE
Do the ignores have lower specificity?

### ISSUE THREAD

**Issue by stubar** [loeffel-io/ls-lint#33]
If I have setup 
```
ls:
  src/pages:
    .tsx: PascalCase | regex:^_.*

ignore:
  - index.tsx
  - src/**/index.tsx
```

I would have expected the creation of a `index.tsx` within `src/pages` to be OK as it's an ignored pattern but it gets caught by the `PascalCase | regex:^_.* ` rule.

I can get around this by using 
```
ignore:
  - index.tsx
  - src/pages/index.tsx
```
Maybe globs aren't recognised in the ignore list?
