### ISSUE TITLE
Slow for my project (1.9.2)

### ISSUE THREAD

**Issue by jfairley** [loeffel-io/ls-lint#42]
First, let me start by saying that I love `ls-lint`. This is one of those things I didn't know I needed until I had it.

However despite the advertised speed, `ls-lint` isn't all that quick for me. I'm wondering if it has to do with my config, and whether you might have tips on what I could change to speed things up. I'm using version 1.9.2.

First, timing (macOS Big Sur on a 2019 16" with an Intel Core i7):

<img width="446" alt="Screen Shot 2021-01-22 at 1 28 19 PM" src="https://user-images.githubusercontent.com/992483/105542917-c68f1080-5cb6-11eb-9b18-1652de6a35d7.png">

Here's my config:

```yml
ls:
  .github/workflows:
    .yml: kebab-case

  cypress:
    fixtures:
      .json: kebab-case
    integration:
      .test.ts: PascalCase

  src:
    .gql: kebab-case
    .svg: kebab-case
    .ts: kebab-case
    .d.ts: kebab-case
    .generated.ts: kebab-case
    .test.ts: kebab-case
    .tsx: PascalCase
    .stories.tsx: PascalCase
    .test.tsx: PascalCase
    hooks:
      .ts: camelCase
      .test.ts: camelCase

ignore:
  - .git/
  - .idea/
  - .nyc_output/
  - build/
  - cypress-coverage/
  - jest-coverage/
  - node_modules/
  - reports/
  - src/index.tsx
  - src/serviceWorker.ts
```

The project is a git repo of React with TypeScript, so there's things like `.git` and `node_modules` to deal with.

Here are some file counts: 

<img width="456" alt="Screen Shot 2021-01-22 at 1 38 59 PM" src="https://user-images.githubusercontent.com/992483/105543673-503ede00-5cb7-11eb-818a-a176ee626b11.png">
