### ISSUE TITLE
Directory names

### ISSUE THREAD

**Issue by binary64** [loeffel-io/ls-lint#46]
Hi I have some regex here https://regex101.com/r/ISyaUy/1

And I try it like this:

```
ls:
  apps:
    .tsx: 'regex:apps\/web\/components\/[a-z-]+[a-z]\/[a-z-]+[a-z](.stories\|.spec)?'
```

But it gives an error:

```
2021/02/27 10:45:04 rule .spec)? not exists
error Command failed with exit code 1.
```

**Comment by loeffel-io** [comment]
Hey @binary64,

the regex alternation`|` is not supported: https://ls-lint.org/1.x/configuration/the-rules.html#using-multiple-regex-rules

So your config should looks like this (not tested): 

```yaml
ls:
  apps/web/components/*:
    .tsx: 'regex:[a-z-]+[a-z](\.stories)? | regex:[a-z-]+[a-z](\.spec)?'  
```
