### ISSUE TITLE
How to set a default rule?

### ISSUE THREAD

**Issue by BryanAdamss** [loeffel-io/ls-lint#50]
Its support set defalut rule for all files?
Just use a special format for a particular type of file?

```yml
ls:
   default: kebab-case // default for all files. When not matched , use kebab-case.
   
   .js: camelCase // .js file use camel case
```
